// 문항 풀 — 어휘·맞춤법·독해·신조어 각 15문항 = 총 60문항.
// 출처: docs/munhae-items-draft.md (은채 작성, 윤진 1차 검수 반영본, 2026-07-15).
// 기준: 국립국어원 표준국어대사전·한국어 어문 규범. answerIndex 는 0-based(①=0).
// 엔진은 pool-agnostic 이므로 앱이 이 배열을 generatePaper 에 주입한다.
//
// ⚠️ 출시 전 사용자 확인(윤진 QA): A05·A11·A14 표준국어대사전 재대조, D10·D15 신조어 최신성.

import type { Item } from "@/lib/munhae-engine";

// A. 어휘 (15)
const VOCAB: Item[] = [
  {
    id: "A01",
    area: "vocab",
    difficulty: 1,
    question: '"심심한 사과의 말씀을 드립니다"에서 \'심심하다\'의 뜻은?',
    choices: ["지루하고 재미없다", "마음의 표현이 깊고 간절하다", "담담하고 덤덤하다", "성의가 없다"],
    answerIndex: 1,
    explain: "심심(甚深)하다: 마음의 표현 정도가 매우 깊고 간절하다",
  },
  {
    id: "A02",
    area: "vocab",
    difficulty: 1,
    question: '안내문의 "금일 휴무"에서 \'금일\'은 언제?',
    choices: ["금요일", "이번 주", "오늘", "지금 이 시간만"],
    answerIndex: 2,
    explain: "금일(今日) = 오늘. 금요일로 오해하는 대표 사례",
  },
  {
    id: "A03",
    area: "vocab",
    difficulty: 1,
    question: '"사흘 뒤에 만나자"에서 \'사흘\'은 며칠?',
    choices: ["2일", "3일", "4일", "7일"],
    answerIndex: 1,
    explain: "하루-이틀-사흘-나흘. '사'흘을 4일로 오해하기 쉬움",
  },
  {
    id: "A04",
    area: "vocab",
    difficulty: 1,
    question: '"부장님께 기안서 ___를 올렸다"',
    choices: ["결제", "결재", "결례", "결산"],
    answerIndex: 1,
    explain: "결재(決裁): 상관이 안건을 승인함 / 결제(決濟): 대금을 치름",
  },
  {
    id: "A05",
    area: "vocab",
    difficulty: 3,
    question: '"그의 침묵은 오히려 죄책감의 ___이다"',
    choices: ["반증", "방증", "검증", "실증"],
    answerIndex: 1,
    explain: "방증(傍證): 간접적으로 증명에 도움을 줌 / 반증: 반대 증거",
  },
  {
    id: "A06",
    area: "vocab",
    difficulty: 1,
    question: "'갈등을 지양하다'에서 '지양'의 뜻은?",
    choices: ["더 높은 곳을 향함", "하지 않도록 피함", "소중히 기름", "그대로 유지함"],
    answerIndex: 1,
    explain: "지양(止揚): 하지 아니함 / 지향(志向): 목표로 향함",
  },
  {
    id: "A07",
    area: "vocab",
    difficulty: 2,
    question: "'미증유의 사태'에서 '미증유'의 뜻은?",
    choices: ["아직 해결되지 않음", "지금까지 한 번도 있어 본 적 없음", "증거가 남지 않음", "예상이 불가능함"],
    answerIndex: 1,
    explain: "미증유(未曾有): 역사상 전례가 없음",
  },
  {
    id: "A08",
    area: "vocab",
    difficulty: 2,
    question: '"마라톤 세계 기록을 ___했다"',
    choices: ["갱신", "경신", "혁신", "쇄신"],
    answerIndex: 1,
    explain: "기록을 깨뜨림 = 경신, 기간 연장 = 갱신 (국립국어원 온라인가나다 기준)",
  },
  {
    id: "A09",
    area: "vocab",
    difficulty: 2,
    question: '"예상 못 한 질문에 ___스러웠다"',
    choices: ["곤욕", "곤혹", "고초", "곤경"],
    answerIndex: 1,
    explain: "곤혹(困惑): 어찌할 바를 모름 / 곤욕(困辱): 심한 모욕을 당함",
  },
  {
    id: "A10",
    area: "vocab",
    difficulty: 2,
    question: '"___를 찾기 어려운 폭염이 이어졌다"',
    choices: ["유래", "유례", "사례", "전래"],
    answerIndex: 1,
    explain: "유례(類例): 비슷한 예 / 유래(由來): 사물의 내력",
  },
  {
    id: "A11",
    area: "vocab",
    difficulty: 2,
    question: '"외부인의 출입을 ___ 금합니다"',
    choices: ["일체", "일절", "일괄", "일임"],
    answerIndex: 1,
    explain: "부정·금지에는 일절(一切), '모든 것'의 명사는 일체",
  },
  {
    id: "A12",
    area: "vocab",
    difficulty: 1,
    question: '"그 결정은 재고할 필요가 있다"에서 \'재고\'의 뜻은?',
    choices: ["창고에 쌓아 둠", "다시 생각함", "없던 일로 함", "윗사람에게 알림"],
    answerIndex: 1,
    explain: "재고(再考): 다시 생각함. 재고(在庫)와 동음이의",
  },
  {
    id: "A13",
    area: "vocab",
    difficulty: 1,
    question: '"네 입장을 십분 이해한다"에서 \'십분\'의 뜻은?',
    choices: ["10분 동안", "아주 충분히", "조금은", "부분적으로"],
    answerIndex: 1,
    explain: "십분(十分): 아주 충분히",
  },
  {
    id: "A14",
    area: "vocab",
    difficulty: 2,
    question: '시험 보러 가는 친구에게 "무운을 빈다"라고 했다. \'무운\'의 뜻은?',
    choices: ["운이 없기를 바람", "싸움에서 이기는 운", "무난한 결과", "아무 일도 없음"],
    answerIndex: 1,
    explain: "무운(武運): 전쟁·경쟁에서의 운수. 無運으로 오해한 사례가 화제였음",
  },
  {
    id: "A15",
    area: "vocab",
    difficulty: 2,
    question: '"그 사건에 대해 그는 끝까지 함구했다"에서 \'함구\'의 뜻은?',
    choices: ["크게 항의함", "입을 다물고 말하지 않음", "사실을 왜곡함", "기억하지 못함"],
    answerIndex: 1,
    explain: "함구(緘口): 입을 다묾",
  },
];

// B. 맞춤법 (15)
const SPELLING: Item[] = [
  {
    id: "B01",
    area: "spelling",
    difficulty: 1,
    question: '바른 표기는? "이제 집에 가도 ___?"',
    choices: ["되", "돼", "됌", "됀"],
    answerIndex: 1,
    explain: "'되어'의 준말 = 돼. 문장 끝에는 '돼'",
  },
  {
    id: "B02",
    area: "spelling",
    difficulty: 1,
    question: '바른 표기는? "숙제를 다 하지 ___"',
    choices: ["안았다", "않았다", "안헀다", "않앗다"],
    answerIndex: 1,
    explain: "'-지 않다'(아니하다의 준말). '안'은 부사(안 했다)",
  },
  {
    id: "B03",
    area: "spelling",
    difficulty: 1,
    question: '바른 표기는? "___이야, 네가 여기까지 오고?"',
    choices: ["왠일", "웬일", "왼일", "웬닐"],
    answerIndex: 1,
    explain: "웬일: 어찌 된 일. '왠'은 '왠지'에서만",
  },
  {
    id: "B04",
    area: "spelling",
    difficulty: 1,
    question: '바른 표기는? "오늘이 ___이지?"',
    choices: ["몇일", "몇 일", "며칠", "몇칠"],
    answerIndex: 2,
    explain: "표준어는 '며칠'. '몇일'은 틀린 표기",
  },
  {
    id: "B05",
    area: "spelling",
    difficulty: 2,
    question: '바른 표기는? "소문이 ___ 퍼졌다"',
    choices: ["금새", "금세", "금세에", "금사이"],
    answerIndex: 1,
    explain: "금세: '금시에'의 준말. '금새'는 물건값을 뜻하는 별개 단어",
  },
  {
    id: "B06",
    area: "spelling",
    difficulty: 1,
    question: '바른 표기는? "정말 ___이야, 잘 지냈어?"',
    choices: ["오랫만", "오랜만", "오랜맛", "오랬만"],
    answerIndex: 1,
    explain: "'오래간만'의 준말 = 오랜만. 단, '오랫동안'은 ㅅ 받침",
  },
  {
    id: "B07",
    area: "spelling",
    difficulty: 2,
    question: '바른 표기는? "참 ___ 일이네"',
    choices: ["희안한", "희한한", "히한한", "희환한"],
    answerIndex: 1,
    explain: "희한(稀罕)하다가 표준어",
  },
  {
    id: "B08",
    area: "spelling",
    difficulty: 2,
    question: '바른 표기는? "내일 생각만 하면 마음이 ___"',
    choices: ["설레인다", "설렌다", "설레진다", "설래인다"],
    answerIndex: 1,
    explain: "기본형은 '설레다'. '설레이다'는 비표준",
  },
  {
    id: "B09",
    area: "spelling",
    difficulty: 2,
    question: '바른 표기는? "사과의 ___를 세어 보자"',
    choices: ["갯수", "개수", "개쑤", "갯쑤"],
    answerIndex: 1,
    explain: "한자어 '개수(個數)'는 사이시옷을 쓰지 않음",
  },
  {
    id: "B10",
    area: "spelling",
    difficulty: 2,
    question: '바른 표기는? "그럼 내일 ___!"',
    choices: ["뵈요", "봬요", "뵈여요", "벼요"],
    answerIndex: 1,
    explain: "'뵈어요'의 준말 = 봬요 ('되/돼'와 같은 원리)",
  },
  {
    id: "B11",
    area: "spelling",
    difficulty: 1,
    question: '바른 표기는? "정말 ___ 상황이었다"',
    choices: ["어의없는", "어이없는", "어예없는", "어히없는"],
    answerIndex: 1,
    explain: "어이없다: 어처구니없다. '어의'는 임금의 의사",
  },
  {
    id: "B12",
    area: "spelling",
    difficulty: 1,
    question: '바른 표기는? "감기 빨리 ___ 바라"',
    choices: ["낳기를", "낫기를", "낮기를", "났기를"],
    answerIndex: 1,
    explain: "병이 낫다 / 아이를 낳다",
  },
  {
    id: "B13",
    area: "spelling",
    difficulty: 2,
    question: '바른 표기는? "학생___ 마땅히 할 일이다"',
    choices: ["으로써", "으로서", "으로써서", "으롯"],
    answerIndex: 1,
    explain: "-로서: 지위·자격 / -로써: 수단·도구",
  },
  {
    id: "B14",
    area: "spelling",
    difficulty: 2,
    question: '바른 표기는? "먹___ 말___ 마음대로 해"',
    choices: ["던지/던지", "든지/든지", "던지/든지", "든지/던지"],
    answerIndex: 1,
    explain: "선택은 '-든지', 과거 회상은 '-던지'",
  },
  {
    id: "B15",
    area: "spelling",
    difficulty: 1,
    question: '바른 표기는? "이 옷은 어디에나 ___하게 어울린다"',
    choices: ["문안", "무난", "무안", "문난"],
    answerIndex: 1,
    explain: "무난(無難)하다: 어려움이 없다. '문안'은 안부를 여쭘",
  },
];

// C. 독해 (15) — 짧은 실용 지문. passage 에 지문, question 에 발문.
const READING: Item[] = [
  {
    id: "C01",
    area: "reading",
    difficulty: 2,
    passage: "1+1 행사 상품은 행사 기간 내 결제 건에 한하며, 타 쿠폰과 중복 적용되지 않습니다.",
    question: "할인 쿠폰을 가진 사람이 행사 상품을 사면?",
    choices: ["1+1과 쿠폰 모두 적용", "1+1과 쿠폰 중 하나만 적용", "쿠폰만 적용", "아무것도 적용 안 됨"],
    answerIndex: 1,
    explain: "'중복 적용되지 않는다' = 둘 중 하나만",
  },
  {
    id: "C02",
    area: "reading",
    difficulty: 1,
    passage: "1일 3회, 1회 2정, 식후 30분에 복용하세요.",
    question: "하루에 먹는 약은 총 몇 정?",
    choices: ["2정", "3정", "5정", "6정"],
    answerIndex: 3,
    explain: "3회 × 2정 = 6정",
  },
  {
    id: "C03",
    area: "reading",
    difficulty: 1,
    passage: "우천 시 행사는 익일로 순연됩니다.",
    question: "행사 날 비가 오면?",
    choices: ["취소된다", "다음 날로 미뤄진다", "실내로 옮긴다", "예정대로 한다"],
    answerIndex: 1,
    explain: "익일 = 다음 날, 순연 = 차례로 미룸",
  },
  {
    id: "C04",
    area: "reading",
    difficulty: 1,
    passage: "본 상품은 단순 변심에 의한 교환·환불이 불가합니다.",
    question: "색상이 마음에 안 들어 환불을 요청하면?",
    choices: ["가능하다", "불가능하다", "교환만 가능하다", "수수료 내면 가능하다"],
    answerIndex: 1,
    explain: "단순 변심 = 하자 없이 마음이 바뀐 경우",
  },
  {
    id: "C05",
    area: "reading",
    difficulty: 1,
    passage: "만 19세 미만은 보호자 동반 시에만 입장 가능합니다.",
    question: "17세가 혼자 오면?",
    choices: ["입장 가능", "입장 불가", "신분증 있으면 가능", "요금을 더 내면 가능"],
    answerIndex: 1,
    explain: "동반 '시에만' = 혼자서는 불가",
  },
  {
    id: "C06",
    area: "reading",
    difficulty: 1,
    passage: "회의는 매주 화요일에 열린다. 다만 화요일이 공휴일인 경우 그 주 수요일로 옮긴다.",
    question: "화요일이 공휴일인 주의 회의는?",
    choices: ["취소", "월요일", "수요일", "다음 주 화요일"],
    answerIndex: 2,
    explain: "예외 조건(다만~) 읽기",
  },
  {
    id: "C07",
    area: "reading",
    difficulty: 1,
    passage: "선착순 100명에 한해 사은품을 드립니다. (1인 1개, 소진 시 조기 종료)",
    question: "101번째로 도착한 사람은?",
    choices: ["1개 받는다", "반 개 받는다", "못 받는다", "다음 날 받는다"],
    answerIndex: 2,
    explain: "'100명에 한해' = 그 범위 안에서만",
  },
  {
    id: "C08",
    area: "reading",
    difficulty: 2,
    passage: "운동은 건강에 좋다. 그러나 준비 없이 강도 높은 운동을 하면 오히려 몸을 해친다. 결국 중요한 것은 자기 몸에 맞는 강도를 찾는 일이다.",
    question: "글의 요지는?",
    choices: [
      "운동은 무조건 많이 할수록 좋다",
      "운동은 건강에 해롭다",
      "자신에게 맞는 강도로 운동해야 한다",
      "준비 운동은 필요 없다",
    ],
    answerIndex: 2,
    explain: "'결국' 뒤에 핵심 주장",
  },
  {
    id: "C09",
    area: "reading",
    difficulty: 3,
    passage: "이번 조사에서 응답자의 60%가 찬성했다. 그러나 표본이 특정 연령대에 치우쳐 있어 이를 전체 여론으로 보기는 어렵다.",
    question: "글쓴이의 의도는?",
    choices: [
      "찬성이 많으니 결론 확정",
      "조사 결과의 일반화를 경계",
      "반대가 더 많다는 주장",
      "조사가 조작됐다는 폭로",
    ],
    answerIndex: 1,
    explain: "표본 편향 → 일반화 주의",
  },
  {
    id: "C10",
    area: "reading",
    difficulty: 1,
    passage: "환승 할인은 하차 후 30분 이내 승차 시 적용됩니다.",
    question: "내린 지 40분 뒤에 다시 타면?",
    choices: ["할인 적용", "할인 없음", "반값 할인", "다음 승차에 적용"],
    answerIndex: 1,
    explain: "조건(30분 이내) 벗어남",
  },
  {
    id: "C11",
    area: "reading",
    difficulty: 2,
    passage: "서류 합격자에 한하여 발표일 당일 개별 통보합니다.",
    question: "발표일이 지났는데 아무 연락이 없다면?",
    choices: ["합격 가능성이 높다", "불합격했을 가능성이 높다", "전형이 연기됐다", "서류가 누락됐다"],
    answerIndex: 1,
    explain: "합격자'에 한하여' 발표일에 통보 = 발표일 이후 무소식은 불합격 신호",
  },
  {
    id: "C12",
    area: "reading",
    difficulty: 2,
    passage: "본 이벤트는 사전 예고 없이 변경 또는 조기 종료될 수 있습니다.",
    question: "이 문장이 뜻하는 바는?",
    choices: ["이벤트는 끝까지 유지된다", "조건이 언제든 바뀔 수 있다", "예고 후에만 바뀐다", "이미 종료됐다"],
    answerIndex: 1,
    explain: "면책 조항 읽기",
  },
  {
    id: "C13",
    area: "reading",
    difficulty: 1,
    passage: "해동 후 재냉동하지 마십시오.",
    question: "냉동식품을 녹였다면?",
    choices: ["다시 얼려도 된다", "다시 얼리면 안 된다", "반만 얼릴 수 있다", "하루 뒤엔 얼려도 된다"],
    answerIndex: 1,
    explain: "재냉동 = 다시 얼림",
  },
  {
    id: "C14",
    area: "reading",
    difficulty: 2,
    passage: "주차권은 발급 당일, 최초 1회 출차 시까지만 유효합니다.",
    question: "차를 뺐다가 다시 들어오면?",
    choices: ["같은 주차권 사용 가능", "주차권을 새로 받아야 한다", "다음 날까지 유효", "2회까지 무료"],
    answerIndex: 1,
    explain: "'최초 1회 출차 시까지' = 나가는 순간 효력 끝",
  },
  {
    id: "C15",
    area: "reading",
    difficulty: 1,
    passage: "구매 후 7일 이내, 미개봉 상품에 한해 환불이 가능합니다.",
    question: "3일 전에 사서 개봉한 상품은?",
    choices: ["환불 가능", "환불 불가", "7일 뒤 가능", "개봉해도 기간 내면 가능"],
    answerIndex: 1,
    explain: "두 조건(기간 AND 미개봉) 모두 충족해야 함",
  },
];

// D. 신조어 — 역문해력 (15) ※ 출시 시점 최신성 재확인
const SLANG: Item[] = [
  {
    id: "D01",
    area: "slang",
    difficulty: 1,
    question: "'점메추'의 뜻은?",
    choices: ["점심 메뉴 추천", "점심 메이트 추가", "점수 메기고 추천", "점점 메마르고 추움"],
    answerIndex: 0,
    explain: "점심+메뉴+추천",
  },
  {
    id: "D02",
    area: "slang",
    difficulty: 1,
    question: "'갓생'의 뜻은?",
    choices: ["갓 태어난 삶", "부지런하고 모범적인 삶", "신을 믿는 삶", "갓 시작한 인생"],
    answerIndex: 1,
    explain: "God+인생: 계획적으로 사는 삶",
  },
  {
    id: "D03",
    area: "slang",
    difficulty: 1,
    question: "'억까'의 뜻은?",
    choices: ["억지로 깎아내림", "억울하게 까임 방지", "억대 연봉 까발림", "매우 가까움"],
    answerIndex: 0,
    explain: "억지+까다: 근거 없는 비난",
  },
  {
    id: "D04",
    area: "slang",
    difficulty: 2,
    question: "'스불재'의 뜻은?",
    choices: ["스스로 불러온 재앙", "스타일 불변의 재능", "스트레스로 불면 재발", "스승의 불호령 재현"],
    answerIndex: 0,
    explain: "자업자득의 신조어 버전",
  },
  {
    id: "D05",
    area: "slang",
    difficulty: 1,
    question: "'알잘딱깔센'의 뜻은?",
    choices: [
      "알아서 잘 딱 깔끔하고 센스 있게",
      "알고 보니 잘난 척",
      "알바를 잘 딱 골라 깔끔하게",
      "알림을 잘 딱 꺼두는 센스",
    ],
    answerIndex: 0,
    explain: "다섯 단어의 앞 글자 조합",
  },
  {
    id: "D06",
    area: "slang",
    difficulty: 1,
    question: "'국룰'의 뜻은?",
    choices: ["국가의 법률", "보편적으로 통하는 암묵적 규칙", "국어 룰렛", "국내 한정 룰"],
    answerIndex: 1,
    explain: "국민+룰: 다들 그렇게 하는 것",
  },
  {
    id: "D07",
    area: "slang",
    difficulty: 2,
    question: "'캘박'의 뜻은?",
    choices: ["캘린더에 박제(일정 확정)", "캐릭터 박스", "캘리그래피 박람회", "캐리어를 박살냄"],
    answerIndex: 0,
    explain: "약속을 캘린더에 저장해 확정",
  },
  {
    id: "D08",
    area: "slang",
    difficulty: 1,
    question: "'답정너'의 뜻은?",
    choices: ["답을 정해 두고 묻는 사람", "답장이 정말 넘치는 너", "답답한 정서의 너", "정답을 너무 잘 아는 사람"],
    answerIndex: 0,
    explain: "답은 정해져 있으니 너는 대답만 해",
  },
  {
    id: "D09",
    area: "slang",
    difficulty: 2,
    question: "'삼귀다'의 뜻은?",
    choices: ["사귀기 전의 썸 단계", "세 명이 함께 사귐", "세 번째로 사귐", "삼가서 사귐"],
    answerIndex: 0,
    explain: "사귀다의 '사(4)'보다 하나 낮은 '삼(3)'",
  },
  {
    id: "D10",
    area: "slang",
    difficulty: 2,
    question: "'럭키비키'의 뜻은?",
    choices: ["운이 좋다는 초긍정 감탄", "행운의 마스코트 인형", "복권 당첨 인증", "럭셔리한 휴가"],
    answerIndex: 0,
    explain: '아이브 장원영의 초긍정 사고("완전 럭키비키잖아")에서 유행',
  },
  {
    id: "D11",
    area: "slang",
    difficulty: 1,
    question: "'갑분싸'의 뜻은?",
    choices: ["갑자기 분위기 싸해짐", "갑부의 분위기 있는 싸인", "갑옷 분해 싸움", "갑자기 분식이 싸짐"],
    answerIndex: 0,
    explain: "실언 등으로 분위기가 얼어붙는 상황",
  },
  {
    id: "D12",
    area: "slang",
    difficulty: 2,
    question: "'반모'의 뜻은?",
    choices: ["반말 모드", "반대 모임", "반쪽 모자", "반성 모드"],
    answerIndex: 0,
    explain: "서로 반말하기로 한 사이",
  },
  {
    id: "D13",
    area: "slang",
    difficulty: 2,
    question: "'만반잘부'의 뜻은?",
    choices: ["만나서 반가워 잘 부탁해", "만사 반대 잘못된 부탁", "만점 반은 잘한 부분", "만두 반죽 잘 붙음"],
    answerIndex: 0,
    explain: "온라인 첫인사 축약",
  },
  {
    id: "D14",
    area: "slang",
    difficulty: 1,
    question: '"요즘 폼 미쳤다"의 뜻은?',
    choices: ["자세가 흐트러졌다", "기량·상태가 아주 좋다", "옷차림이 이상하다", "화가 많이 났다"],
    answerIndex: 1,
    explain: "폼(form): 컨디션·기량에 대한 극찬",
  },
  {
    id: "D15",
    area: "slang",
    difficulty: 2,
    question: "'테토남'의 뜻은?",
    choices: ["터프하고 주도적인 매력의 남자", "테니스를 잘 치는 남자", "테스트를 통과한 남자", "토라진 남자"],
    answerIndex: 0,
    explain: "테스토스테론에서 유래한 성향 밈 (에겐남과 대비)",
  },
];

/** 전체 문항 풀 60개 (어휘15·맞춤법15·독해15·신조어15) */
export const ITEMS: Item[] = [...VOCAB, ...SPELLING, ...READING, ...SLANG];
